name: Tests
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - develop
      - topic-exchange
      - master
  push:
    branches:
      - develop
      - topic-exchange
      - master

jobs:
  build:
    services:
      rabbitmq:
        image: rabbitmq:3.11-alpine
        ports:
          - 5672:5672
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Fix up git URLs
      run: echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig

    - name: Check out code
      uses: actions/checkout@v1
      with:
        fetch-depth: 15
        submodules: true
        token: ${{ secrets.BLOB }}

    - name: Set up Go
      id: go
      timeout-minutes: 10
      uses: actions/setup-go@v3
      with:
        go-version: '1.23'
        cache: true

    - name: Test
      run: |
        export PATH=$PATH:/tmp/protoc/bin:/home/runner/go/bin
        export GO111MODULE=on
        export GOPROXY=https://proxy.golang.org
        go get github.com/golang/protobuf/protoc-gen-go@v1.3.2
        go get github.com/golang/mock/mockgen@v1.6.0
        go get github.com/getkalido/gener8
        go get github.com/onsi/gomega@v1.16.0
        go get github.com/kisielk/errcheck@v1.5.0
        go get github.com/onsi/ginkgo/ginkgo@v1.16.5
        go install github.com/onsi/ginkgo/ginkgo
        cd test && ginkgo
