name: Tests
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

jobs:
  build:
    services:
      rabbitmq:
        image: rabbitmq:3.7-alpine
        ports:
          - 5672:5672
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Go 1.15.8
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.8
      id: go

    - name: Fix up git URLs
      run: echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig

    - name: Check out code
      uses: actions/checkout@v1
      with:
        fetch-depth: 15
        submodules: true
        token: ${{ secrets.BLOB }}

    - name: go-path-cache
      uses: actions/cache@v1
      with:
        path: /home/runner/go
        key: ${{ runner.os }}-go-path@v1

    - name: Test
      run: |
        export PATH=$PATH:/tmp/protoc/bin:/home/runner/go/bin
        export GO111MODULE=on
        export GOPROXY=https://proxy.golang.org
        go get github.com/golang/protobuf/protoc-gen-go@v1.3.2
        go get github.com/golang/mock/mockgen@v1.6.0
        go get github.com/getkalido/gener8
        go get github.com/onsi/gomega@v1.16.0
        go get github.com/kisielk/errcheck@v1.5.0
        go get github.com/onsi/ginkgo/ginkgo@v1.16.5
        cd test && ginkgo
